cmake_minimum_required(VERSION 4.0)
project(Contest)

set(CMAKE_CXX_STANDARD 20)

add_executable(Contest main.cpp
        contest5/С.cpp
        contest5/D.cpp
        contest5/E.cpp
        contest5/F.cpp
        contest5/G.cpp
        contest5/H.cpp
        6contest/A.cpp
        6contest/B.cpp
        6contest/С.cpp
        6contest/D.cpp
        6contest/E.cpp
        6contest/F.cpp
        6contest/G.cpp
        6contest/H.cpp
        contest7/A.cpp
        contest7/B.cpp
        contest7/C.cpp
        contest7/D.cpp
        contest7/E.cpp
        contest7/F.cpp
        contest7/G.cpp
        contest7/H.cpp
        contest7/I.cpp
        contest7/J.cpp
        contest8/a.cpp
        contest8/b.cpp
        contest8/C.cpp
        contest8/D.cpp)
