cmake_minimum_required(VERSION 4.0)
project(Midtern)

set(CMAKE_CXX_STANDARD 20)

add_executable(Midtern main.cpp
        demo1/1task.cpp
        demo1/1task.cpp
        demo1/2try.cpp
        demo1/2try.cpp
        demo1/main.cpp
        demo1/main.cpp
        demo1/1.cpp
        demo1/2.cpp
        demo1/3.cpp
        demo1/4.cpp
        demo1/5.cpp
        demo1/5.cpp
        demo1/1.cpp
        mid/1.cpp
        mid/2.cpp
        mid/3.cpp
        mid/4.cpp
        mid/5.cpp
)
