cmake_minimum_required(VERSION 4.0)
project(Midtern)

set(CMAKE_CXX_STANDARD 20)

add_executable(Midtern main.cpp
        demo1/1task.cpp
        demo1/1task.cpp
        demo1/2try.cpp
        demo1/2try.cpp
        demo1/main.cpp
        demo1/main.cpp
        demo1/1.cpp
        demo1/2.cpp
        demo1/3.cpp
        demo1/4.cpp
        demo1/5.cpp
        demo1/5.cpp
        demo1/1.cpp
        mid/1.cpp
        mid/2.cpp
        mid/3.cpp
        mid/4.cpp
        mid/5.cpp
        Demo2/main.cpp
        Demo2/3task.cpp
        Demo2/4task.cpp
        Demo2/5task.cpp
        Demo2/11.cpp
        Demo2/22.cpp
        Demo2/33.cpp
        Demo2/44.cpp
        Demo2/55.cpp
        demo0/1.cpp
        demo0/2.cpp
        demo0/3.cpp
        demo0/4.cpp
        demo0/5.cpp
        Mid2/1.cpp
        Mid2/2.cpp
        Mid2/3.cpp
        Mid2/4.cpp
        Mid2/5.cpp
)
